name: Build, Test & Deploy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "setup.py"
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: ./__tests__/setup-pip.sh
      - name: Linter
        run: ./__tests__/linter.sh
      - name: Unittests
        run: python3 -m unittest tests.unittests -v

  publish:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Build Python distribution
        run: |
          pip install wheel
          rm -rf dist
          python setup.py bdist_wheel sdist --formats gztar
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@f3ebf87ba2883f1c40faf37d2bb42277f12179c8
        with:
          user: __token__
          password: ${{ secrets.pypi_api_key }}
